# Generated by Django 4.1.3 on 2022-12-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_saveconcreate_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saveconcreate',
            old_name='Sum_concrete',
            new_name='sum_concrete',
        ),
        migrations.AlterField(
            model_name='saveconcreate',
            name='mark',
            field=models.CharField(max_length=50, verbose_name='Марка бетона'),
        ),
    ]
